processed 15 tasks

task 1 'publish'. lines 8-53:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7790000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 55-63:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4453600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 66-66:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 68-68:
Owner: Shared
Version: 4
Contents: t2::o2::Obj2 {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}}

task 5 'run'. lines 70-70:
mutated: object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 6 'run'. lines 72-72:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'view-object'. lines 74-74:
Owner: Shared
Version: 6
Contents: t2::o2::Obj2 {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}

task 8 'run'. lines 76-76:
mutated: object(0,0)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 9 'run'. lines 78-78:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'run'. lines 80-80:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::freeze_object_impl (function index 6) at offset 0, Abort Code: 1
Cannot return execution error with shared objects. Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 6, instruction: 0, function_name: Some("freeze_object_impl") }, 1) at command Some(0)

task 11 'run'. lines 82-82:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::transfer_impl (function index 8) at offset 0, Abort Code: 0
Cannot return execution error with shared objects. Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 8, instruction: 0, function_name: Some("transfer_impl") }, 0) at command Some(0)

task 12 'run'. lines 84-84:
mutated: object(0,0), object(9,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 13 'run'. lines 86-86:
mutated: object(0,0), object(9,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 14 'run'. lines 88-88:
Error: Transaction Effects Status: Shared objects cannot be wrapped.
Cannot return execution error with shared objects. Debug of error: SharedObjectOperationNotAllowed at command None
